spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2003
    url: jdbc:postgresql://localhost:5432/article_management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
