spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2001
    url: jdbc:postgresql://localhost:5432/mini_project
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 100MB
server:
  port: 8080


