spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2001
    url: jdbc:postgresql://localhost:5432/mini_project
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: jsonhub.info@gmail.com
    password: lbutlyfzoxhxqrxv
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable : true
            required : true
          from: contact@email.com
      from:
        name: Sak
server:
  port: 8080
file:
  uploadPath: src/main/resources/storage/



